/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbantrangsuc.views;

import appbantrangsuc.AppBanTrangSuc;
import appbantrangsuc.Const;
import appbantrangsuc.controller.TaiKhoanController;
import appbantrangsuc.models.TaiKhoan;
import appbantrangsuc.models.TaiKhoanNguoiDung;
import appbantrangsuc.widget.BaseForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author vipvl
 */
public class LoginForm extends BaseForm implements ViewResult {

    /**
     * Creates new form LoginForm
     */
    private TaiKhoanController taiKhoanController;
    private boolean isFromMain;
    private LoginListener listener;

    public void setListener(LoginListener listener) {
        this.listener = listener;
    }
    

    public LoginForm(boolean isMain) {
        this.isFromMain = isMain;
        taiKhoanController = new TaiKhoanController(this);
        initComponents();
        if (this.isFromMain) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        lbError.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new appbantrangsuc.widget.CustomPanel();
        logoLabel = new javax.swing.JLabel();
        customPanel2 = new appbantrangsuc.widget.CustomPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        imageLabel1 = new appbantrangsuc.widget.ImageLabel();
        customPanel3 = new appbantrangsuc.widget.CustomPanel();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customPanel1.setBackground(new java.awt.Color(255, 255, 255));
        customPanel1.setForeground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("MAKE COLOR SHOP");

        customPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        fieldUsername.setBackground(new java.awt.Color(204, 204, 204));
        fieldUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        fieldPass.setBackground(new java.awt.Color(204, 204, 204));
        fieldPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout customPanel2Layout = new javax.swing.GroupLayout(customPanel2);
        customPanel2.setLayout(customPanel2Layout);
        customPanel2Layout.setHorizontalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPass)
                    .addComponent(fieldUsername)))
        );
        customPanel2Layout.setVerticalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pictures/sanpham/icon_user.png"))); // NOI18N
        imageLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        customPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSignIn.setBackground(new java.awt.Color(51, 255, 51));
        btnSignIn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSignInClick(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(51, 102, 255));
        btnSignUp.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSignUpClick(evt);
            }
        });

        javax.swing.GroupLayout customPanel3Layout = new javax.swing.GroupLayout(customPanel3);
        customPanel3.setLayout(customPanel3Layout);
        customPanel3Layout.setHorizontalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        customPanel3Layout.setVerticalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnContinue.setBackground(new java.awt.Color(255, 255, 0));
        btnContinue.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnContinue.setLabel("Continue without account");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onContinueClick(evt);
            }
        });

        lbError.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        lbError.setForeground(new java.awt.Color(0, 51, 51));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbError.setText("Tai khoan hoac mat khau khong dung");

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                        .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(customPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 96, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(customPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(customPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSignInClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSignInClick
        // TODO add your handling code here:
        TaiKhoan taiKhoan = new TaiKhoan();
        taiKhoan.setTaiKhoan(fieldUsername.getText().trim());
        char[] pass = fieldPass.getPassword();
        taiKhoan.setPass(String.valueOf(pass));
        taiKhoanController.login(taiKhoan);
    }//GEN-LAST:event_onSignInClick

    private void onSignUpClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSignUpClick
        // TODO add your handling code here:
        new SignUpForm(false).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_onSignUpClick

    private void onContinueClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onContinueClick
        // TODO add your handling code here:
        new MainDisplayScreen().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_onContinueClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private appbantrangsuc.widget.CustomPanel customPanel1;
    private appbantrangsuc.widget.CustomPanel customPanel2;
    private appbantrangsuc.widget.CustomPanel customPanel3;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUsername;
    private appbantrangsuc.widget.ImageLabel imageLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onViewResultSuccess(int key, Object... data) {
        if (key == Const.ACCOUNT_QUERY_ALL) {
            List<TaiKhoan> l = (List<TaiKhoan>) data[0];
            if (l.isEmpty()) {
                lbError.setVisible(true);
            } else {
                TaiKhoan taiKhoan = l.get(0);
                TaiKhoanNguoiDung.getInstance().distroy();
                TaiKhoanNguoiDung.getInstance(taiKhoan);
                AppBanTrangSuc.isAdmin = TaiKhoanNguoiDung.getInstance().getPermission() == 0;
                if (!this.isFromMain) {
                    new MainDisplayScreen().setVisible(true);
                }
                else {
                    listener.onSuccess();
                    System.out.println("login success");
                }
                this.dispose();
            }
        }
    }

    @Override
    public void onViewResultFailed(String mess) {
        if (this.isFromMain) {
            listener.onFailed();
        }
    }
    
    public interface LoginListener {
        void onSuccess();
        void onFailed();
    }
}
