/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbantrangsuc.views;

import appbantrangsuc.AppBanTrangSuc;
import appbantrangsuc.Const;
import appbantrangsuc.controller.TaiKhoanController;
import appbantrangsuc.models.TaiKhoan;
import appbantrangsuc.models.TaiKhoanNguoiDung;
import appbantrangsuc.widget.BaseForm;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vipvl
 */
public class SignUpForm extends BaseForm implements ViewResult{

    private TaiKhoanController taiKhoanController;
    private final String TAI_KHOAN_DA_TON_TAI = "Tai Khoan Nay Da Ton Tai";
    private final String MAT_KHAU_NHAP_LAI_KHONG_KHOP = "Mat Khau Nhap Lai Khong Khop";
    private final boolean isAddFromMain;
    /**
     * Creates new form SignInForm
     * @param isAddFromMain
     */
    public SignUpForm(boolean isAddFromMain) {
        this.isAddFromMain = isAddFromMain;
        taiKhoanController = new TaiKhoanController(this);
        initComponents();
        if (isAddFromMain) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        lbError1.setVisible(true);
        panelPermisson.setVisible(AppBanTrangSuc.isAdmin);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new appbantrangsuc.widget.CustomPanel();
        logoLabel = new javax.swing.JLabel();
        customPanel2 = new appbantrangsuc.widget.CustomPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        imageLabel1 = new appbantrangsuc.widget.ImageLabel();
        customPanel3 = new appbantrangsuc.widget.CustomPanel();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        customPanel4 = new appbantrangsuc.widget.CustomPanel();
        logoLabel1 = new javax.swing.JLabel();
        customPanel5 = new appbantrangsuc.widget.CustomPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldUsername1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPass1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        fieldConfirm = new javax.swing.JPasswordField();
        imageLabel2 = new appbantrangsuc.widget.ImageLabel();
        customPanel6 = new appbantrangsuc.widget.CustomPanel();
        btnCreate = new javax.swing.JButton();
        lbError1 = new javax.swing.JLabel();
        panelPermisson = new appbantrangsuc.widget.CustomPanel();
        rbAdmin = new javax.swing.JRadioButton();
        rbNormal = new javax.swing.JRadioButton();

        logoLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Login");

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        fieldUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        fieldPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout customPanel2Layout = new javax.swing.GroupLayout(customPanel2);
        customPanel2.setLayout(customPanel2Layout);
        customPanel2Layout.setHorizontalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPass)
                    .addComponent(fieldUsername)))
        );
        customPanel2Layout.setVerticalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pictures/sanpham/icon_user.png"))); // NOI18N
        imageLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSignIn.setBackground(new java.awt.Color(51, 255, 51));
        btnSignIn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInonSignInClick(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(51, 102, 255));
        btnSignUp.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUponSignUpClick(evt);
            }
        });

        javax.swing.GroupLayout customPanel3Layout = new javax.swing.GroupLayout(customPanel3);
        customPanel3.setLayout(customPanel3Layout);
        customPanel3Layout.setHorizontalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        customPanel3Layout.setVerticalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnContinue.setBackground(new java.awt.Color(255, 255, 0));
        btnContinue.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnContinue.setLabel("Continue without account");

        lbError.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 0, 0));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbError.setText("Tai khoan hoac mat khau khong dung");

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                        .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(customPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 78, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(customPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addComponent(customPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap())
        );

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        logoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel1.setText("Đăng Ký");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Tài Khoản:");

        fieldUsername1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldUsername1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Mật Khẩu:");

        fieldPass1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldPass1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Nhập Lại:");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        fieldEmail.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        fieldConfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fieldConfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout customPanel5Layout = new javax.swing.GroupLayout(customPanel5);
        customPanel5.setLayout(customPanel5Layout);
        customPanel5Layout.setHorizontalGroup(
            customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customPanel5Layout.createSequentialGroup()
                        .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPass1)
                            .addComponent(fieldUsername1)))
                    .addGroup(customPanel5Layout.createSequentialGroup()
                        .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEmail)
                            .addComponent(fieldConfirm, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        customPanel5Layout.setVerticalGroup(
            customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pictures/sanpham/icon_user.png"))); // NOI18N
        imageLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnCreate.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnCreate.setText("Tạo");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateClick(evt);
            }
        });

        javax.swing.GroupLayout customPanel6Layout = new javax.swing.GroupLayout(customPanel6);
        customPanel6.setLayout(customPanel6Layout);
        customPanel6Layout.setHorizontalGroup(
            customPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        customPanel6Layout.setVerticalGroup(
            customPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbError1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        lbError1.setForeground(new java.awt.Color(255, 0, 0));
        lbError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rbAdmin.setText("Admin");
        rbAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdminChecked(evt);
            }
        });

        rbNormal.setSelected(true);
        rbNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rbNormal.setLabel("Normal");
        rbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNormalChecked(evt);
            }
        });

        javax.swing.GroupLayout panelPermissonLayout = new javax.swing.GroupLayout(panelPermisson);
        panelPermisson.setLayout(panelPermissonLayout);
        panelPermissonLayout.setHorizontalGroup(
            panelPermissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPermissonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPermissonLayout.setVerticalGroup(
            panelPermissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPermissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbAdmin)
                .addComponent(rbNormal))
        );

        javax.swing.GroupLayout customPanel4Layout = new javax.swing.GroupLayout(customPanel4);
        customPanel4.setLayout(customPanel4Layout);
        customPanel4Layout.setHorizontalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(customPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(customPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPermisson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        customPanel4Layout.setVerticalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel4Layout.createSequentialGroup()
                .addComponent(logoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPermisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbError1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(customPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInonSignInClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInonSignInClick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSignInonSignInClick

    private void btnSignUponSignUpClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUponSignUpClick
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSignUponSignUpClick

    private void onCreateClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateClick
        // TODO add your handling code here:
        
        String pass = String.valueOf(fieldPass1.getPassword());
        String conf = String.valueOf(fieldConfirm.getPassword());
        if ( !pass.equals(conf)) {
            lbError1.setText(MAT_KHAU_NHAP_LAI_KHONG_KHOP);
            lbError1.setVisible(true);
            return;
        }
        int per = -1;
        if (!AppBanTrangSuc.isAdmin) {
            per = 1;
        }
        else{
            if (rbAdmin.isSelected()) {
                per = 0;
            }
            else if (rbNormal.isSelected()) {
                per = 1;
            }
        }
        TaiKhoan taiKhoan = new TaiKhoan(
                fieldUsername1.getText().trim(),
                String.valueOf(fieldPass1.getPassword()),
                fieldEmail.getText(),
                per);
        taiKhoanController.signup(taiKhoan);
    }//GEN-LAST:event_onCreateClick

    private void onAdminChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdminChecked
        // TODO add your handling code here:
        rbNormal.setSelected(false);
    }//GEN-LAST:event_onAdminChecked

    private void onNormalChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNormalChecked
        // TODO add your handling code here:
        rbAdmin.setSelected(false);
    }//GEN-LAST:event_onNormalChecked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private appbantrangsuc.widget.CustomPanel customPanel1;
    private appbantrangsuc.widget.CustomPanel customPanel2;
    private appbantrangsuc.widget.CustomPanel customPanel3;
    private appbantrangsuc.widget.CustomPanel customPanel4;
    private appbantrangsuc.widget.CustomPanel customPanel5;
    private appbantrangsuc.widget.CustomPanel customPanel6;
    private javax.swing.JPasswordField fieldConfirm;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JPasswordField fieldPass1;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JTextField fieldUsername1;
    private appbantrangsuc.widget.ImageLabel imageLabel1;
    private appbantrangsuc.widget.ImageLabel imageLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbError1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoLabel1;
    private appbantrangsuc.widget.CustomPanel panelPermisson;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbNormal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onViewResultSuccess(int key, Object... data) {
        if (key == Const.ACCOUNT_QUERY_INSERT) {
            if (isAddFromMain) {
                JOptionPane.showMessageDialog(this, "Them Tai Khoan Thanh Cong", "Success", JOptionPane.PLAIN_MESSAGE);
                return;
            }
            taiKhoanController.login((TaiKhoan) data[0]);
        }
        if (key == Const.ACCOUNT_QUERY_ALL) {
            List<TaiKhoan> l = (List<TaiKhoan>) data[0];
            if (l.isEmpty()) {
                lbError.setVisible(true);
            } else {
                TaiKhoan taiKhoan = l.get(0);
                TaiKhoanNguoiDung.getInstance().distroy();
                TaiKhoanNguoiDung.getInstance(taiKhoan);
                AppBanTrangSuc.isAdmin = TaiKhoanNguoiDung.getInstance().getPermission() == 0;
                new MainDisplayScreen().setVisible(true);
                this.dispose();
            }
        }
    }

    @Override
    public void onViewResultFailed(String mess) {
        System.out.println(mess);
        if (mess.equals("Violation of PRIMARY KEY constraint 'PK_TaiKhoan'."
                + " Cannot insert duplicate key in object 'dbo.TaiKhoan'."
                + " The duplicate key value is ("+ fieldUsername1.getText().trim() +").")) {
            lbError1.setText(TAI_KHOAN_DA_TON_TAI);
            lbError1.setVisible(true);
        }
    }
}
