/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbantrangsuc.views;

import appbantrangsuc.AppBanTrangSuc;
import appbantrangsuc.controller.SanPhamController;
import appbantrangsuc.models.SanPham;
import appbantrangsuc.utils.AppUtils;
import appbantrangsuc.utils.NumberFilter;
import appbantrangsuc.views.interfaces.FormListener;
import appbantrangsuc.widget.BaseForm;
import javax.swing.JFrame;
import javax.swing.text.PlainDocument;

/**
 *
 * @author vipvl
 */
public class XemSanPham extends BaseForm {

    private static XemSanPham instance;
    private SanPhamController sanPhamController;

    private int sl = 0;

    public static XemSanPham getInstance(SanPham sanPham, SanPhamController sanPhamController) {
        if (instance == null) {
            instance = new XemSanPham(sanPham, sanPhamController);
        }
        return instance;
    }

    /**
     * Creates new form XemSanPham
     */
    private SanPham sanPham;

    private XemSanPham() {
        initComponents();
    }

    private XemSanPham(SanPham sanPham, SanPhamController sanPhamController) {
        this.sanPham = sanPham;
        this.sanPhamController = sanPhamController;
        initComponents();
        PlainDocument doc = (PlainDocument) slSp.getDocument();
        doc.setDocumentFilter(new NumberFilter<>(Integer.class));
        updateSlSp();
        this.tenSp.setText(this.sanPham.getTenSanPham());
        this.giaSanPham.setText(String.format("Price: %.2f", sanPham.getGiaSanPham()));
        String mt = "<html><p style=\"width:" + 200 + "px\">" + "Details: " + this.sanPham.getMoTa() + "</p></html>";
        this.moTaSanPham.setText(mt);
        this.image.setIcon(AppUtils.resizeIcon(this.sanPham.getImageLabel().getIcon(), imgPanel));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenSp = new javax.swing.JLabel();
        giaSanPham = new javax.swing.JLabel();
        moTaSanPham = new javax.swing.JLabel();
        muaHangBtn = new javax.swing.JButton();
        themVaoGioHangBtn = new javax.swing.JButton();
        imgPanel = new appbantrangsuc.widget.CustomPanel();
        image = new appbantrangsuc.widget.ImageLabel();
        customPanel1 = new appbantrangsuc.widget.CustomPanel();
        minusSp = new javax.swing.JButton();
        slSp = new javax.swing.JTextField();
        plusSp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tenSp.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        tenSp.setText("Ten San Pham");

        giaSanPham.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        giaSanPham.setText("Gia");

        moTaSanPham.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        moTaSanPham.setText("Mo ta");
        moTaSanPham.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moTaSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        moTaSanPham.setOpaque(true);

        muaHangBtn.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        muaHangBtn.setText("Mua Hàng");
        muaHangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMuaHang(evt);
            }
        });

        themVaoGioHangBtn.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        themVaoGioHangBtn.setText("Them Vao Gio Hang");
        themVaoGioHangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onThemVaoGioHang(evt);
            }
        });

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        customPanel1.setBackground(new java.awt.Color(0, 255, 51));

        minusSp.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        minusSp.setForeground(new java.awt.Color(255, 0, 0));
        minusSp.setText("-");
        minusSp.setBorder(null);
        minusSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMinusClick(evt);
            }
        });

        slSp.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        slSp.setForeground(new java.awt.Color(255, 0, 0));
        slSp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        slSp.setText("1");
        slSp.setBorder(null);

        plusSp.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        plusSp.setForeground(new java.awt.Color(255, 0, 0));
        plusSp.setText("+");
        plusSp.setBorder(null);
        plusSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlusClick(evt);
            }
        });

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minusSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slSp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plusSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(plusSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slSp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenSp, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addComponent(giaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moTaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(themVaoGioHangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(muaHangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenSp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(giaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moTaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muaHangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themVaoGioHangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onMuaHang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMuaHang
        // TODO add your handling code here:

    }//GEN-LAST:event_onMuaHang

    private void onThemVaoGioHang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onThemVaoGioHang
        // TODO add your handling code here:

    }//GEN-LAST:event_onThemVaoGioHang

    private void onPlusClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPlusClick
        // TODO add your handling code here:
        sl++;
        updateSlSp();
    }//GEN-LAST:event_onPlusClick

    private void onMinusClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMinusClick
        // TODO add your handling code here:
        if (sl > 0) {
            sl--;
            updateSlSp();
        }

    }//GEN-LAST:event_onMinusClick

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private appbantrangsuc.widget.CustomPanel customPanel1;
    private javax.swing.JLabel giaSanPham;
    private appbantrangsuc.widget.ImageLabel image;
    private appbantrangsuc.widget.CustomPanel imgPanel;
    private javax.swing.JButton minusSp;
    private javax.swing.JLabel moTaSanPham;
    private javax.swing.JButton muaHangBtn;
    private javax.swing.JButton plusSp;
    private javax.swing.JTextField slSp;
    private javax.swing.JLabel tenSp;
    private javax.swing.JButton themVaoGioHangBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() {
        instance = null;
        super.dispose();
    }

    private void updateSlSp() {
        slSp.setText(String.format("%d", sl));
    }

    
}
